sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t mamuz/phalcon-application .
  - docker run --rm -it mamuz/phalcon-application ./vendor/bin/codecept run

script:
  - ./vendor/bin/codecept run
